### ISSUE TITLE
Measurement issues

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/extended-data-model#56] opened 2022-09-26 05:52 UTC
In the following there is a mismatch between measurement count in the 2 indicated places. Also not sure why the actual measurement values have no space between the value and its unit of measure.

![Screen Shot 2022-09-26 at 3 51 47 pm](https://user-images.githubusercontent.com/8326394/192203135-a7235d97-bb95-4977-84bd-11ea68e4d748.png)

**Comment by qifeng-bai** [comment] 2022-11-02 23:48
There is also a bug, when you click 'Sample'
![Screen Shot 2022-11-03 at 10 47 04 am](https://user-images.githubusercontent.com/31238531/199623056-11b5509a-692e-4ec4-9c30-d4978f18e930.png)

**Comment by qifeng-bai** [comment] 2022-11-08 06:00
I suspect it is not UI issue. It is caused by GraphQL service.

When we send [the quest to fetch 6003295-1-1](https://events-test.ala.org.au/graphql?queryId=f47b01f9e8c50fba1aa947807c3d9555be31378a&strict=true&variables=%7B%22predicate1%22:%7B%22type%22:%22and%22,%22predicates%22:[%7B%22key%22:%22eventHierarchy%22,%22type%22:%22equals%22,%22value%22:%226003295-1-1%22%7D,%7B%22key%22:%22datasetKey%22,%22type%22:%22equals%22,%22value%22:%22dr18391%22%7D]%7D,%22predicate2%22:%7B%22type%22:%22and%22,%22predicates%22:[%7B%22key%22:%22eventHierarchy%22,%22type%22:%22equals%22,%22value%22:%226003295-1-1%22%7D,%7B%22key%22:%22measurementOrFactTypes%22,%22type%22:%22isNotNull%22%7D,%7B%22key%22:%22datasetKey%22,%22type%22:%22equals%22,%22value%22:%22dr18391%22%7D]%7D,%22size%22:0,%22from%22:0%7D)

The size of measurements is from

`       "eventTypeHierarchyJoined": [
          {
            "key": "Survey / SiteVisit / Sample / Find",
            "count": 1
          }
        ]`

However, it has 2 measurements: 
`"measurementOrFacts": [
              {
                "measurementID": "ep_m1_public_data.fid--5c8f4e3e_17f8c23325f_-5e00-biomass",
                "measurementType": "biomass",
                "measurementValue": "372.5421",
                "measurementUnit": "g"
              },
              {
                "measurementID": "ep_m1_public_data.fid--5c8f4e3e_17f8c23325f_-5e00-size",
                "measurementType": "sizeClass",
                "measurementValue": "15",
                "measurementUnit": "cm"
              }
            ]`

Another example is:   [query 6003295-1](https://events-test.ala.org.au/graphql?queryId=242281047ea7ffc165a68229fff51d48a905732f&strict=true&variables=%7B%22eventID%22:%226003295-1%22,%22datasetKey%22:%22dr18391%22%7D)

It returns

`"eventTypeHierarchyJoined": [
          {
            "key": "Survey / SiteVisit / Sample / Find",
            "count": 88
          }
        ]`

and 

` "measurementOrFactTypes": [
          {
            "count": 88,
            "key": "biomass"
          },
          {
            "count": 88,
            "key": "sizeClass"
          },
          {
            "count": 1,
            "key": "transectBlock"
          }
        ]`

**Comment by qifeng-bai** [comment] 2022-11-09 05:15
@charvolant  and I reckon that Find == Occurrence, Measurement should be under Occurrence/Find. 

![Screen Shot 2022-11-09 at 4 10 38 pm](https://user-images.githubusercontent.com/31238531/200744431-1a8d4d75-68c2-4acb-869f-4cbd3aaed575.png)

**Comment by qifeng-bai** [comment] 2022-11-10 03:01
ES returns me measurementOrFactCount: null, 
https://events-test.ala.org.au/es/event?apiKey=my-api-key&eventID=6002910-0

**Comment by qifeng-bai** [comment] 2022-11-11 04:54
@javier-molina The fix has been deployed on events-test

**Comment by qifeng-bai** [comment] 2022-11-11 05:01
PR: https://github.com/gbif/gbif-web/pull/196
including API support

**Comment by javier-molina** [comment] 2022-11-16 04:50
@qifeng-bai  Looking good overall but either Seedbank dataset is stretching the system or there is a bug 

Filtering by event [1667479-trial-4422](https://events-test.ala.org.au/?datasetKey=dr18527&eventHierarchy=1667479-trial-4422&view=EVENTS) does not bring all the MoF. There are plenty of them, occurrence is not displayed either in the tree hierarchy. See screenshots below

Probably @charvolant can shed some light when he is back.

![Screen Shot 2022-11-16 at 3 44 57 pm](https://user-images.githubusercontent.com/8326394/202085938-0a0b5e48-814e-4763-a1fb-34007eb76a0f.png)

![Screen Shot 2022-11-16 at 3 38 24 pm](https://user-images.githubusercontent.com/8326394/202086406-e1f0a144-59c0-48cb-bfef-1e92e24e9f8a.png)

**Comment by qifeng-bai** [comment] 2022-11-17 00:43
https://events-test.ala.org.au/es/event?apiKey=my-api-key&eventID=6002910-0
returns mesuarements,

but for 1667479-trial-4422
https://events-test.ala.org.au/es/event?apiKey=my-api-key&eventID=1667479-trial-4422
there is no measurements in result

**Comment by djtfmartin** [comment] 2022-11-17 13:46
I've now fixed this in this PR: https://github.com/gbif/pipelines/pull/809

The issue was caused by the archive for seedbanks (correctly) using the extended measurement of fact extension.

<img width="1475" alt="Screen Shot 2022-11-17 at 1 47 45 pm" src="https://user-images.githubusercontent.com/444897/202463114-5270ad6a-162b-4c5a-af31-e93903dddaa1.png">

**Comment by qifeng-bai** [comment] 2022-11-23 21:58
PR https://github.com/gbif/gbif-web/pull/209

**Closed as completed** 2022-11-24 12:40 UTC
Labels: bug
